### ISSUE TITLE
How to use SENSV with bam files that I already have?

### ISSUE THREAD

**Issue by giuliafrascarelli** [HKU-BAL/SENSV#6]
Hi,
thank you for this nice software! I am working with barley nanopore data and I already have bam files that I previously produced with minimap2. Since it took so much time I wonder if there is a way to use SENSV starting from bam files 

Thank you

**Comment by ccbruels** [comment]
Hi, were you able to get sensv working with existing bam files? I was thinking about running minimap separately, then commenting out that part of the sensv code to see if that will work.

**Comment by bbvan** [comment]
Hello @giuliafrascarelli and @ccbruels, 

SENSV works by utilizing the reads chaining information which is computed on-the-fly by minimap2. That chaining information is not contained in the bam files, and unfortunately, the tool minimap2 does not provide any options to retrieve it. As a result, our modified version of minimap2 has to be used to save those chaining information.

The best possible workaround would be first extracting fastq from the bam files using `samtools fastq my.bam > my.fastq` and then run SENSV from fastq files. Hope this helps.
